colorScheme = "custom-colors"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = true
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
highlightCurrentMenuArea = true
githubViewPath = "https://github.com/QubiTO-team/qubito-website/"
githubEditPath = "https://github.com/QubiTO-team/qubito-website/edit/main/content/"
isRecruiting = false
isQuantumDaysRegistrationOpen = false
googleScriptUrl = "https://script.google.com/macros/s/AKfycbzQcoGTi7cL0mqLoT01KvvT4rTrNGWpHV71-pesLrKqg5t2UfhFmz-xtgNe4pOfdGA/exec"

[header]
layout = "fixed"
HasChildren = true

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "custom"
showRecent = true
showRecentItems = 5
showMoreLink = true
showMoreLinkDest = "articles"
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false
layoutBackgroundBlur = true

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = true
showWordCount = true
showZenMode = false
hideFeatureImage = true
showDescription = true
showCategory = true
draft = false


[list]
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = false
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = true
showCards = true
cardViewScreenWidth = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
showCards = true
cardViewScreenWidth = false

[firebase]

[analytics]
enabled = false

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]

[rssnext]
